# -*- coding: utf-8 -*-
"""Clima.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bowRJfU7UBUQQhCG7Io8o_4kRspK2-x9
"""

horario = "noite"
clima = "Amena"
temperatura = "quente"

if horario == "manha" or horario == "tarde":
    if clima == "ensolarado" and temperatura == "quente":
       print("Uma piscina cairia bem")
    if (clima == "ensolarado" or clima == "nublado") and (temperatura == "amena" or temperatura == "Fria"):
      print("Seria legal praticar algum esporte")
    if clima == "chuvoso":
      print("Aproveite para treinar seu python")
else:
    if clima == "chuvoso":
      print("Que tal um filme, serie ou jogatina?")
    else:
      print("Um jantar fora parece interessante...")

